### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by EmilMaric** [josuebrunel/yahoo-fantasy-sport#46]
Not a burning issue, but it would be nice to have the code conform to **PEP 8** standards, as listed [here](https://www.python.org/dev/peps/pep-0008/). Makes the code a little easier to follow.

**Comment by josuebrunel** [comment]
Yeah sure :wink:

**Comment by josuebrunel** [comment]
@EmilMaric  by the way, you should check @unpairestgood 's [repo](https://github.com/unpairestgood/yahoo-fantasy-sport), which has already some great features. I was supposed to check why his tests were failing, but i didn't find a time to do that. I will try to do something about it this weekend

**Comment by EmilMaric** [comment]
I'll take a look.
